POST https://localhost:5001/api/CronJob
Content-Type: application/json

{
  "cron": "0 0 * * *",
  "timeZone": "UTC",
  "title": "Sample Cron Job",
  "data": "Sample data",
  "runImmediately": false,
  "isPaused": false,
  "isDeleted": false,
  "updatedAt": "2024-08-11T17:05:43-0400",
  "createdAt": "2024-08-11T17:05:43-0400"
}
